[versions]
dev-funixgaming-spring-core = "1.4.2"

[libraries]
dev-funixgaming-core-crud = { module = "dev.funixgaming.spring.core.crud:crud", version.ref = "dev-funixgaming-spring-core" }
dev-funixgaming-core-storage = { module = "dev.funixgaming.spring.core.storage:storage", version.ref = "dev-funixgaming-spring-core" }
